import type { OrderItemProps } from "@/features/order/types";

export const TABS = [
{ label: "هفته جاری", value: "current week" },
{ label: "هفته آینده", value: "feature week" },
] as const;

export const FAKE_ORDERS: OrderItemProps[][] = [
  [
    { mealType: 'breakfast', mealName: 'کره مربا', mealCount: 71 },
    { mealType: 'breakfast', mealName: 'نان و پنیر', mealCount: 381 },
    { mealType: 'breakfast', mealName: 'نوتلا', mealCount: 98 },
    { mealType: 'breakfast', mealName: 'کره بادام‌زمینی', mealCount: 31 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 100 },
    { mealType: 'lunch', mealName: 'خورشت هویج', mealCount: 131 },
    { mealType: 'lunch', mealName: 'چلوکباب', mealCount: 691 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 10 },
    { mealType: 'lunch', mealName: 'خورشت فسنجان', mealCount: 311 },
    { mealType: 'lunch', mealName: 'خورشت قیمه', mealCount: 571 },
    { mealType: 'dinner', mealName: 'خورشت قیمه‌بادمجان', mealCount: 211 },
    { mealType: 'dinner', mealName: 'چلو کباب', mealCount: 161 },
    { mealType: 'dinner', mealName: 'چلومرغ', mealCount: 38 },
    { mealType: 'dinner', mealName: 'چلو جوجه‌کباب', mealCount: 58 },
    { mealType: 'dinner', mealName: 'خورشت قیمه', mealCount: 47 },
    { mealType: 'dinner', mealName: 'خورشت قورمه‌سبزی', mealCount: 70 },
  ],
  [
    { mealType: 'breakfast', mealName: 'نان و پنیر', mealCount: 12 },
    { mealType: 'breakfast', mealName: 'کره بادام‌زمینی', mealCount: 4 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 2 },
    { mealType: 'lunch', mealName: 'خورشت هویج', mealCount: 591 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 731 },
    { mealType: 'lunch', mealName: 'خورشت قیمه', mealCount: 52 },
    { mealType: 'lunch', mealName: 'خورشت قیمه‌بادمجان', mealCount: 96 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 671 },
    { mealType: 'dinner', mealName: 'چلو جوجه‌کباب', mealCount: 111 },
    { mealType: 'dinner', mealName: 'خورشت قیمه', mealCount: 72 },
    { mealType: 'dinner', mealName: 'خورشت قورمه‌سبزی', mealCount: 150 },
  ],
  [
    { mealType: 'breakfast', mealName: 'کره مربا', mealCount: 79 },
    { mealType: 'breakfast', mealName: 'کره بادام‌زمینی', mealCount: 91 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 401 },
    { mealType: 'lunch', mealName: 'خورشت هویج', mealCount: 751 },
    { mealType: 'lunch', mealName: 'چلوکباب', mealCount: 25 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 91 },
    { mealType: 'lunch', mealName: 'خورشت قیمه‌بادمجان', mealCount: 44 },
    { mealType: 'dinner', mealName: 'چلو کباب', mealCount: 80 },
    { mealType: 'dinner', mealName: 'چلومرغ', mealCount: 461 },
    { mealType: 'dinner', mealName: 'خورشت قیمه', mealCount: 151 },
    { mealType: 'dinner', mealName: 'خورشت قورمه‌سبزی', mealCount: 331 },
  ],
  [
    { mealType: 'breakfast', mealName: 'کره مربا', mealCount: 79 },
    { mealType: 'breakfast', mealName: 'نان و پنیر', mealCount: 8 },
    { mealType: 'breakfast', mealName: 'کره بادام‌زمینی', mealCount: 39 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 871 },
    { mealType: 'lunch', mealName: 'خورشت هویج', mealCount: 1 },
    { mealType: 'lunch', mealName: 'چلوکباب', mealCount: 951 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 44 },
    { mealType: 'lunch', mealName: 'خورشت فسنجان', mealCount: 341 },
    { mealType: 'dinner', mealName: 'خورشت قیمه', mealCount: 641 },
    { mealType: 'dinner', mealName: 'خورشت قیمه‌بادمجان', mealCount: 66 },
    { mealType: 'dinner', mealName: 'چلومرغ', mealCount: 491 },
    { mealType: 'dinner', mealName: 'خورشت قورمه‌سبزی', mealCount: 331 },
  ],
  [
    { mealType: 'breakfast', mealName: 'کره مربا', mealCount: 181 },
    { mealType: 'lunch', mealName: 'خورشت هویج', mealCount: 539 },
    { mealType: 'lunch', mealName: 'چلوکباب', mealCount: 85 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 57 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 18 },
    { mealType: 'lunch', mealName: 'خورشت قیمه', mealCount: 44 },
    { mealType: 'lunch', mealName: 'خورشت قیمه‌بادمجان', mealCount: 341 },
    { mealType: 'dinner', mealName: 'چلو کباب', mealCount: 58 },
    { mealType: 'dinner', mealName: 'چلومرغ', mealCount: 151 },
    { mealType: 'dinner', mealName: 'خورشت قورمه‌سبزی', mealCount: 431 },
  ],
  [
    { mealType: 'breakfast', mealName: 'چلومرغ', mealCount: 201 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 5 },
    { mealType: 'lunch', mealName: 'چلوکباب', mealCount: 7 },
    { mealType: 'lunch', mealName: 'چلومرغ', mealCount: 531 },
    { mealType: 'dinner', mealName: 'خورشت قیمه', mealCount: 93 },
    { mealType: 'dinner', mealName: 'چلو کباب', mealCount: 53 },
    { mealType: 'dinner', mealName: 'چلومرغ', mealCount: 68 },
    { mealType: 'dinner', mealName: 'چلو جوجه‌کباب', mealCount: 41 },
    { mealType: 'dinner', mealName: 'خورشت قورمه‌سبزی', mealCount: 79 },
  ],
  [
    { mealType: 'breakfast', mealName: 'چلومرغ', mealCount: 23 },
    { mealType: 'lunch', mealName: 'چلو جوجه‌کباب', mealCount: 5 },
    { mealType: 'lunch', mealName: 'خورشت قیمه', mealCount: 291 },
    { mealType: 'dinner', mealName: 'خورشت هویج', mealCount: 95 },
    { mealType: 'dinner', mealName: 'خورشت قیمه‌بادمجان', mealCount: 65 },
  ],
];